### ISSUE TITLE
Update to lastest

### ISSUE THREAD

**Issue by AndersBrohus-MySupport** [christopherrobinson/Font-Awesome-Icons#1]
Hi :)

Can these be upgraded to the latest version of FA? :)

**Comment by christopherrobinson** [comment]
This has now been updated to v5.12.1

I'm not as actively involved in Umbraco these days (the original project I generated these for was Umbraco based) so I don't have really have a need for this repository anymore - that said; I'll give myself an hour or two next week to play around with automating the updates moving forward as I'm aware a few people find it useful.

**Comment by AndersBrohus-MySupport** [comment]
Nice thanks alot! :D
